const { metadataForProduct } = require("./product-metadata");

const products = [
  {
    id: "thorn-vase",
    slug: "thorn-vase",
    name: "660",
    description: "A tall industrial form made to sharpen delicate silhouettes.",
    priceCents: 7000,
    currency: "eur",
    imageUrl: "/assets/responsive/render-6-1280.webp",
    galleryImages: ["/assets/responsive/render-6-1280.webp", "/assets/shop/660-vase-01.jpg"],
    inventory: 8,
    serialNumbers: [1, 2, 3, 4, 5, 6, 7, 8],
    editionSize: 8,
    active: true,
    ...metadataForProduct("thorn-vase"),
  },
  {
    id: "column-vase",
    slug: "column-vase",
    name: "120",
    description: "A restrained vertical vessel with a cast, architectural texture.",
    priceCents: 15000,
    currency: "eur",
    imageUrl: "/assets/responsive/render-3-900.webp",
    galleryImages: ["/assets/responsive/render-3-900.webp", "/assets/shop/120-vase-01.jpg", "/assets/shop/120-vase-02.jpg"],
    inventory: 12,
    serialNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    editionSize: 12,
    active: true,
    ...metadataForProduct("column-vase"),
  },
  {
    id: "round-vase",
    slug: "round-vase",
    name: "490",
    description: "A low, weighty volume balancing soft growth and hard material.",
    priceCents: 25000,
    currency: "eur",
    imageUrl: "/assets/responsive/round-vase-900.webp",
    galleryImages: ["/assets/responsive/round-vase-900.webp", "/assets/shop/490-vase-01.jpg", "/assets/shop/490-vase-02.jpg"],
    inventory: 10,
    serialNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    editionSize: 10,
    active: true,
    ...metadataForProduct("round-vase"),
  },
];

module.exports = { products };
